# Generated by Django 5.2.6 on 2025-10-31 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_supportmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Від адміністратора')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Відправник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chat', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Повідомлення чату',
                'verbose_name_plural': 'Чат підтримки',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SupportMessage',
        ),
    ]
