# Generated by Django 5.2.6 on 2025-11-03 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_supportchat_delete_supportmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Додаткова інформація')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата замовлення')),
                ('status', models.CharField(default='Нове', max_length=50, verbose_name='Статус')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service', verbose_name='Послуга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Замовлення послуги',
                'verbose_name_plural': 'Замовлення послуг',
            },
        ),
    ]
