# Generated by Django 5.2.6 on 2025-11-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
