# Generated by Django 5.2.6 on 2025-11-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportchat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
